### PR TITLE
Cyrillic fonts table fixes

### PR DESCRIPTION
**Pull request by 1upus**
fontinfo_large.xml and fontinfo_medium.xml width table fixes for glyphs indexed 275-340

### CODE REVIEW

**Comment by chyyran** [comment]
The width values are generated from the NFTR files, could you elaborate on what exactly was changed and how you came up with those values?

**Comment by 1upus** [comment]
Table width for cyrillic glyphs was fixed
fontinfo_large

**Comment by chyyran** [comment]
How were those values determined?

**Comment by 1upus** [comment]
Fonts was dumped and was fixed manually with NFTR editing tool while making Zelda Four Swords russian translation.
Fixed font vs original

**Comment by chyyran** [comment]
Thanks

**Comment by 1upus** [comment]
You are welcome

**Comment by 1upus** [comment]
Maybe you can generate new fonts for DSi menu ++ with cyrillic glyphs using this fixed data, or can tell me, what I need to do, to add russian fonts to DSiM++?
Thx

**Comment by chyyran** [comment]
With the way fonts work currently with TWiLightMenu++, it's not possible since there's only so much VRAM available to work with when everything renders on a single layer. NTFR works using sprites, but the DSi Menu theme of TWLM++ doesn't use sprite memory.

**Pull request merged**
